### ISSUE TITLE
Home - Maxim Calender 버튼을 클릭 시 나타나는 헤더 구현하기

### ISSUE THREAD

**Issue by albireo3754** [boostcampwm-2021/iOS10-JipJung#112]
## 설명
Maxim 화면에서 상단 캘린더 아이콘을 클릭하면 위 처럼 아이콘이 변합니다. 이 뷰를 구현합니다.

## To-do List
- [ ] 헤더에서 내려오는 뷰 구현하기
- [ ] 버튼, 헤더 컴포넌트를 캘린더를 클릭했을 때와 돌아 갔을 때 두 화면으로 구현하기
- [ ] 오른쪽에 있는 네비게이터 화면을 클릭하면 오늘 날짜로 돌아가기

## 추가할 사항
![IMG_0B60ACBE3549-1](https://user-images.githubusercontent.com/40790219/142154187-ac002e5d-212a-4af4-b483-ffe7e79c9c71.jpeg)
