### ISSUE TITLE
Focus - Breath 모드 기능 보완

### ISSUE THREAD

**Issue by jogiking** [boostcampwm-2021/iOS10-JipJung#125]
## 설명
- Breath 모드의 기능을 보완한다
- 기록 저장, 추가 애니메이션 구현

## To-do List
- [x] stop 버튼을 눌렀을 때 현재까지의 기록을 저장한다
- [x] start 버튼을 눌렀을 때 카운트 다운하는 애니메이션을 구현
- [x] inhale, exhale하는 애니메이션 구현
- [ ] 파티클 애니메이션 구현

## 사용할 기술
- CAAnimation
