### ISSUE TITLE
모드 전환 기능

### ISSUE THREAD

**Issue by hyunsik-0h** [boostcampwm-2021/iOS10-JipJung#126]
## 설명
모드 전환 버튼을 눌렀을 때 UI/ Animation 변경을 구현합니다.

## To-do List
- [x] 모드 정보를 담고 있는 구독 가능한 싱글톤 객체 Mode 구현.
- [x] 각 화면은 Mode 객체를 구독하고 변경이 일어나면 UI/ Animation을 해당 모드에 맞게 그리도록 구현.
- [x] 모드에 따른 UI/ Animation 상세 구현.
