### ISSUE TITLE
음원 관련 목록을 제공하는 CollectionView 구현

### ISSUE THREAD

**Issue by soohyeon0487** [boostcampwm-2021/iOS10-JipJung#132]
## 설명
- 최근 재생, 선호 음원을 확인 할 수 있는 CollectionView 구현

## To-do List
- [x] 최근 재생 음원 목록
- [x] 선호 음원 목록
- [ ] 주제별 목록 (all 버튼 누르면 나오는 화면)
