### ISSUE TITLE
음원 상세 화면: 사용자가 볼 음원 정보 화면 틀 구현

### ISSUE THREAD

**Issue by jogiking** [boostcampwm-2021/iOS10-JipJung#29]
## 설명
사용자가 볼 음원 상세 화면 틀을 구현한다.

음원 제목, 부제, tag, mode를 화면에 표시

## To-do List
- [ ] 제목을 화면에 표시 
- [ ] 부제를 화면에 표시
- [ ] tag를 화면에 표시
- [ ] mode를 화면에 표시
