### ISSUE TITLE
Home - 일반: 음원 정보 Cell을 구현

### ISSUE THREAD

**Issue by albireo3754** [boostcampwm-2021/iOS10-JipJung#30]
## 설명
- 음원 정보를 간략히 나타내는 Cell을 구현한다. Cell은 동그라미 + 텍스트로 구성되어있다.
- 예상시간: 2시간
## To-do List
- [ ] CustomViewCell을 코드로 구현한다. 
- [ ] Cell 내부에 오토레이아웃으로 위치를 정한다.
- [ ] 중앙의 이미지 뷰에 이미지 로딩 전 기본 이미지를 설정한다.
