### ISSUE TITLE
프로젝트 설정

### ISSUE THREAD

**Issue by soohyeon0487** [boostcampwm-2021/iOS10-JipJung#5]
## 설명
프로젝트 기본 설정 작업

## To-do List
- [x] Commit Template 생성
- [x] PR Template 생성
- [x] Project Binary Merge 설정
