### ISSUE TITLE
리팩토링 - 앱 초기화 부분 수정

### ISSUE THREAD

**Issue by jogiking** [boostcampwm-2021/iOS10-JipJung#86]
## 설명
앱 초기화(Firebase, InnerDB 초기화, AudioSession 초기화) 부분을 Appdelegate에서 처리하도록 변경한다
InnerDB는 앱 최초 실행할 때만 초기화 하도록 수정한다

## To-do List
- [ ] firebase 초기화 부분을 Appdelegate에서 처리하도록 한다
- [ ] InnerDB 초기화 부분을 Appdelegate에서 처리하도록 한다
- [ ] InnerDB 초기화는 앱 최초 실행할 때만 초기화한다
- [ ] AudioSession 초기화 부분을 Appdelegate에서 처리하도록 한다
- [ ] Home 화면쪽에서 초기화 하던 부분을 삭제한다
