### ISSUE TITLE
Explore - SearchViewController 리팩토링, 검색기능

### ISSUE THREAD

**Issue by hyunsik-0h** [boostcampwm-2021/iOS10-JipJung#90]
## 설명
UI 만 구현된 SearchViewController에 검색 기능을 구현한다.

## To-do List
- [x] 기존 Cancel 버튼 바인딩 방식을 RxCocoa 방식으로 변경한다.
- [x] Navigation으로 보여지도록 변경한다.
- [x] 검색 기능을 구현한다.
- [ ] 검색화면 전환 애니매이션 추가 구현 필요.

## 사용할 기술
- RxCocoa
