### ISSUE TITLE
Home - 음악재생: 음원 삭제

### ISSUE THREAD

**Issue by soohyeon0487** [boostcampwm-2021/iOS10-JipJung#95]
## 설명
배경 콜렉션 뷰를 길게 누르면 삭제 여부를 묻는 창을 띄우고 사용자의 선택에 따라 삭제한다.

## To-do List
- [ ] 길게 누르면 Alert를 띄운다
- [ ] 삭제를 누르면 내부 DB의 모드 목록에서 해당 음원을 지운다
- [ ] 삭제를 누르면 내부 Filemanager를 통해 캐시를 지운다.
